keys: &all
  - &kyaru_elizabeth age1zke99l06jf9xc9jjcclncr7fcl4fekrrtza3urt3z3wkawnhr42srgfn6l
  - &kyaru_carmina age13xy60eaa0nvgjhrlzlq3uggqkydw0ffyjmg9teezwy8a0n2g39usm0rkfz
  - &nightmare age1wrwljs4xl8j2wunsqhevamdxg42xxyyz25wr0yf49qcnschlkccqy46jtq
  - &caon age14n5fh458xxdcxm8nldhdfagqln8gddvkwvve4h7yv5f4rjf833hqtzu4z2
  - &elizabeth age107rl7v3mggzr0nalfv9mu0uwwt9cmfevgy0prek52dfe7txklchqm4uvss
  - &carmina age184acq6z5t4tg6n5k90catgrrfq24r7vh3em8sgm4uufe6l99narsr6v4tq
  - &diabolos age1lpkttympmv36x9hm75nt6qa3f6sql8ews3h83s4l3aemw4d4lp9smklutt
  - &twinkle_wish age1t0gc2xe4az2rkcax45jlt0jlvxjul7ru74p6hkt7aeehjlz63ahsfnttqq
  - &little_lyrical age1fxg5vkk8qtf4a9adsg8y8csfeh90gp6vptkvf242c23665788yjs0rmdzh
  - &forester age16xeheucfldekwe7yjyjxmzer0czdf4pf8hw9gg76yefygwcxnveqkvyud3
creation_rules:
  - path_regex: hosts/secrets/[^/]+\.(y(a)ml|json|env|ini|raw|bin)$
    key_groups:
      - age: *all
  - path_regex: secrets/v/[^/]+\.(y(a)ml|json|env|ini|raw|bin)$
    key_groups:
      - age: *all
  - path_regex: hosts/nightmare/secrets/[^/]+\.(y(a)ml|json|env|ini|raw|bin)$
    key_groups:
      - age:
          - *kyaru_elizabeth
          - *kyaru_carmina
          - *nightmare
  - path_regex: hosts/twinkle-wish/secrets/[^/]+\.(y(a)ml|json|env|ini|raw|bin)$
    key_groups:
      - age:
          - *kyaru_elizabeth
          - *kyaru_carmina
          - *twinkle_wish
  - path_regex: hosts/diabolos/secrets/[^/]+\.(y(a)ml|json|env|ini|raw|bin)$
    key_groups:
      - age:
          - *kyaru_elizabeth
          - *kyaru_carmina
          - *diabolos
  - path_regex: hosts/([^/]+/)?secret.nix
    key_groups:
      - age:
          - *kyaru_elizabeth
          - *kyaru_carmina
