# DragonflyDB 1.39.0 copies nixpkgs' RE-flex source into an autotools
# ExternalProject.  RE-flex 5.2.2 was generated by automake 1.16, but nixpkgs'
# 6.0.0 source was generated by automake 1.18.  Dragonfly's nativeBuildInputs
# deliberately provide automake116x, so make sees timestamp skew after the copy,
# tries to regenerate with aclocal-1.18, and fails.
#
# Pin only the source passed to Dragonfly to its upstream-tested 5.2.2 release.
# Remove this overlay once nixpkgs builds Dragonfly's reflex dependency directly
# (or otherwise stops running the copied source's autotools regeneration rules).
{ fetchFromGitHub }:

fetchFromGitHub {
  owner = "Genivia";
  repo = "RE-flex";
  tag = "v5.2.2";
  hash = "sha256-oLpgY8m0hwLrTVkUwxVW7O7vr4Hl7Bn+uIQwFEVSfvc=";
}
