name: "Nix flake update"
on:
  pull_request:
push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install AWS CLI
      if: ${{ env.ACT }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        unzip -q /tmp/awscliv2.zip -d /tmp
        rm /tmp/awscliv2.zip
        sudo /tmp/aws/install --update
        rm -rf /tmp/aws/
    - name: Setup AWS profile
      env:
        AWS_CREDENTIALS: ${{ secrets.aws_credentials }}
        NIX_SECRET_KEY: ${{ secrets.nix_secret_key }}
      run: |
        aws configure set endpoint_url https://usc1.contabostorage.com
        echo -n "$AWS_CREDENTIALS" > ~/.aws/credentials
        mkdir -p ~/.config/nix
    # https://github.com/orgs/community/discussions/26351
    # https://stackoverflow.com/questions/75536771/github-runner-out-of-disk-space-after-building-docker-image
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          accept-flake-config = true
    - name: Setup Nix profile
      env:
        NIX_SECRET_KEY: ${{ secrets.nix_secret_key }}
      run: |
        mkdir -p ~/.config/nix
        echo -n "$NIX_SECRET_KEY" > ~/.config/nix/secret-key
        chmod 0600 ~/.aws/credentials ~/.config/nix/secret-key
        echo "substituters = https://nix-community.cachix.org https://cuda-maintainers.cachix.org https://cache.nixos.org s3://nix-cache?scheme=https&endpoint=usc1.contabostorage.com&secret-key=$(realpath ~/.config/nix/secret-key) " >> ~/.config/nix/nix.conf
        echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= kyaru-nix-cache-1:Zu6gS5WZt4Kyvi95kCmlKlSyk+fbIwvuuEjBmC929KM= cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E=" >> ~/.config/nix/nix.conf
        nix run nixpkgs#sd -- -f s ' +nixConfig =.*\};\n' '' flake.nix
    - name: Copy to S3
      run: ./scripts/copy.sh
    # - name: Build all targets
    #   run: nix build ".#naiveproxy" ".#caddy-naive" ".#nixosConfigurations.caon.config.system.build.toplevel" ".#nixosConfigurations.elizabeth.config.system.build.toplevel" ".#homeConfigurations.kyaru.activation-script" -L
    # - run: nix flake check
